package com.nanbeiyule.game.mahjong;

/**
 * Frame rects of the original mahjong GameLayer sheet.
 *
 * <p>Generated by android/tools/extract_original_taizhou_mahjong_table_assets.py
 * from the original CocoStudio plists. Do not edit by hand.
 *
 * <p>Each frame is {@code {atlasX, atlasY, width, height, rotated}}. A rotated
 * frame occupies a {@code height x width} region in the atlas and must be turned
 * back counter-clockwise to obtain the upright {@code width x height} image.
 */
public final class TaizhouMahjongGameLayerAtlas {
    private TaizhouMahjongGameLayerAtlas() {}

    /** Android resource name of the taizhou_mahjong_game_layer atlas bitmap. */
    public static final String GAME_LAYER_RESOURCE = "taizhou_mahjong_game_layer";

    /** taizhou_mahjong_game_layer atlas bitmap size. */
    public static final int GAME_LAYER_WIDTH = 1024;

    public static final int GAME_LAYER_HEIGHT = 2048;

    /** Frame names of taizhou_mahjong_game_layer, aligned with GAME_LAYER_FRAMES. */
    public static final String[] GAME_LAYER_NAMES = {
        "copy_icon.png",
        "fenxiang_type.png",
        "head_boy.png",
        "head_girl.png",
        "img_close.png",
        "jiankangyouxi.png",
        "mah_banker_flag.png",
        "mah_btn_buda.png",
        "mah_btn_close.png",
        "mah_btn_qishoukou.png",
        "mah_btn_rule.png",
        "mah_btn_yazi_0.png",
        "mah_btn_yazi_0s.png",
        "mah_btn_yazi_1.png",
        "mah_btn_yazi_1s.png",
        "mah_btn_yazi_2.png",
        "mah_btn_yazi_2s.png",
        "mah_cancel_btn.png",
        "mah_clock_bg.png",
        "mah_clock_east.png",
        "mah_clock_east_1.png",
        "mah_clock_east_2.png",
        "mah_clock_east_3.png",
        "mah_clock_north.png",
        "mah_clock_north_1.png",
        "mah_clock_north_2.png",
        "mah_clock_north_3.png",
        "mah_clock_south.png",
        "mah_clock_south_1.png",
        "mah_clock_south_2.png",
        "mah_clock_south_3.png",
        "mah_clock_west.png",
        "mah_clock_west_1.png",
        "mah_clock_west_2.png",
        "mah_clock_west_3.png",
        "mah_copy_btn.png",
        "mah_dd_btn.png",
        "mah_dd_icon.png",
        "mah_dun_btn.png",
        "mah_flag_buda.png",
        "mah_flag_qishoukou.png",
        "mah_gamestart_btn.png",
        "mah_head_bg.png",
        "mah_host_flag.png",
        "mah_invite_btn.png",
        "mah_jiabei_btn.png",
        "mah_jiabei_icon.png",
        "mah_left_bg.png",
        "mah_md_btn.png",
        "mah_md_icon.png",
        "mah_mdd_info_bg.png",
        "mah_msg_btn.png",
        "mah_online_list_btn.png",
        "mah_power_bar.png",
        "mah_power_bg.png",
        "mah_ready.png",
        "mah_roomnum_bg.png",
        "mah_set_btn.png",
        "mah_sp_roomnum.png",
        "mah_speak_btn.png",
        "mah_sys_bg.png",
        "mah_ting_btn.png",
        "mah_ting_icon.png",
        "mah_tuoguan_btn.png",
        "mah_wait_mdd_bg.png",
        "mah_ya_zi.png",
        "mahjong_guohu.png",
        "menu_red_point.png",
        "next_btn.png",
        "share_select_bg.png",
        "share_select_title_bg.png",
        "show_win_lost.png",
        "shuffle_skip.png",
        "shuffle_xipaiquan.png",
        "weixin_icon.png",
        "wifi_icon_1.png",
        "wifi_icon_2.png",
        "wifi_icon_3.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_game_layer. */
    public static final int[][] GAME_LAYER_FRAMES = {
        {148, 861, 127, 127, 0},
        {792, 29, 213, 64, 0},
        {626, 513, 150, 150, 0},
        {792, 500, 150, 150, 0},
        {601, 1739, 99, 102, 1},
        {792, 2, 214, 25, 0},
        {549, 1173, 62, 62, 0},
        {767, 1113, 244, 73, 0},
        {732, 1668, 99, 102, 1},
        {767, 1038, 244, 73, 0},
        {554, 999, 70, 67, 0},
        {148, 1760, 275, 139, 1},
        {272, 1491, 275, 139, 0},
        {272, 1350, 275, 139, 0},
        {613, 1219, 275, 139, 1},
        {272, 1209, 275, 139, 0},
        {272, 1068, 275, 139, 0},
        {626, 942, 275, 139, 1},
        {792, 95, 205, 205, 0},
        {549, 1559, 58, 44, 0},
        {549, 1513, 58, 44, 0},
        {609, 1496, 121, 241, 0},
        {754, 1435, 121, 241, 1},
        {549, 1467, 58, 44, 0},
        {549, 1421, 58, 44, 0},
        {148, 1517, 241, 122, 1},
        {148, 1274, 241, 122, 1},
        {549, 1375, 58, 44, 0},
        {549, 1329, 58, 44, 0},
        {767, 1188, 241, 122, 0},
        {148, 1031, 241, 122, 1},
        {549, 1283, 58, 44, 0},
        {549, 1237, 58, 44, 0},
        {754, 1312, 121, 241, 1},
        {272, 1632, 121, 241, 1},
        {278, 789, 346, 136, 0},
        {277, 927, 275, 139, 0},
        {558, 1702, 40, 41, 1},
        {635, 1872, 101, 101, 0},
        {148, 990, 126, 39, 0},
        {815, 708, 126, 39, 0},
        {278, 651, 346, 136, 0},
        {855, 1666, 105, 106, 1},
        {549, 1068, 67, 71, 1},
        {278, 513, 346, 136, 0},
        {289, 1755, 274, 138, 1},
        {549, 1137, 71, 34, 0},
        {732, 1558, 121, 108, 0},
        {626, 665, 275, 139, 1},
        {515, 1702, 40, 41, 1},
        {767, 708, 130, 46, 1},
        {532, 1943, 101, 101, 0},
        {855, 1558, 106, 106, 0},
        {999, 188, 37, 18, 1},
        {991, 302, 53, 28, 1},
        {815, 749, 88, 122, 0},
        {767, 873, 255, 103, 0},
        {429, 1858, 101, 101, 0},
        {778, 652, 149, 54, 0},
        {532, 1840, 101, 101, 0},
        {767, 978, 255, 58, 0},
        {429, 1755, 101, 101, 0},
        {549, 1605, 95, 53, 1},
        {705, 1769, 101, 101, 0},
        {2, 873, 1163, 144, 1},
        {767, 708, 130, 46, 1},
        {905, 749, 121, 34, 1},
        {963, 1558, 40, 40, 0},
        {140, 513, 346, 136, 1},
        {2, 2, 788, 509, 0},
        {944, 544, 327, 74, 1},
        {2, 513, 346, 136, 1},
        {944, 500, 77, 42, 0},
        {554, 927, 70, 70, 0},
        {792, 302, 196, 197, 1},
        {999, 157, 29, 21, 1},
        {999, 126, 29, 21, 1},
        {999, 95, 29, 21, 1},
    };

    /** Returns the frame index of {@code name} in {@code names}, or -1. */
    public static int indexOf(String[] names, String name) {
        for (int index = 0; index < names.length; index++) {
            if (names[index].equals(name)) {
                return index;
            }
        }
        return -1;
    }
}
