package com.nanbeiyule.game.mahjong;

/**
 * Frame rects of the original Taizhou (areaId 7109) tile-face atlas.
 *
 * <p>Generated by android/tools/extract_original_taizhou_mahjong_assets.py from
 * the original {@code mahlayer_mah_face_2.plist}. Do not edit by hand.
 *
 * <p>Every frame is stored rotated 90 degrees clockwise in the atlas, so a
 * renderer must read a {@code height x width} region and rotate it back
 * counter-clockwise to obtain the upright {@code width x height} face.
 */
public final class TaizhouMahjongFaceAtlas {
    /** Atlas bitmap width in pixels. */
    public static final int ATLAS_WIDTH = 1024;

    /** Atlas bitmap height in pixels. */
    public static final int ATLAS_HEIGHT = 1024;

    /** Upright width of every tile face in pixels. */
    public static final int FACE_WIDTH = 140;

    /** Upright height of every tile face in pixels. */
    public static final int FACE_HEIGHT = 158;

    /**
     * Atlas origin of every face, as {@code {tileId, atlasX, atlasY}} triples
     * ordered by tile id. The occupied region is
     * {@code FACE_HEIGHT x FACE_WIDTH} because the frame is rotated.
     */
    public static final int[][] FRAMES = {
        {17, 2, 854}, // 0x11 万1 CHARACTER
        {18, 802, 712}, // 0x12 万2 CHARACTER
        {19, 642, 712}, // 0x13 万3 CHARACTER
        {20, 482, 712}, // 0x14 万4 CHARACTER
        {21, 322, 712}, // 0x15 万5 CHARACTER
        {22, 162, 712}, // 0x16 万6 CHARACTER
        {23, 2, 712}, // 0x17 万7 CHARACTER
        {24, 802, 570}, // 0x18 万8 CHARACTER
        {25, 642, 570}, // 0x19 万9 CHARACTER
        {33, 482, 570}, // 0x21 条1 BAMBOO
        {34, 322, 570}, // 0x22 条2 BAMBOO
        {35, 162, 570}, // 0x23 条3 BAMBOO
        {36, 2, 570}, // 0x24 条4 BAMBOO
        {37, 802, 428}, // 0x25 条5 BAMBOO
        {38, 642, 428}, // 0x26 条6 BAMBOO
        {39, 482, 428}, // 0x27 条7 BAMBOO
        {40, 322, 428}, // 0x28 条8 BAMBOO
        {41, 162, 428}, // 0x29 条9 BAMBOO
        {49, 2, 428}, // 0x31 筒1 DOT
        {50, 802, 286}, // 0x32 筒2 DOT
        {51, 642, 286}, // 0x33 筒3 DOT
        {52, 482, 286}, // 0x34 筒4 DOT
        {53, 322, 286}, // 0x35 筒5 DOT
        {54, 162, 286}, // 0x36 筒6 DOT
        {55, 2, 286}, // 0x37 筒7 DOT
        {56, 802, 144}, // 0x38 筒8 DOT
        {57, 642, 144}, // 0x39 筒9 DOT
        {65, 482, 144}, // 0x41 风1 WIND
        {66, 322, 144}, // 0x42 风2 WIND
        {67, 162, 144}, // 0x43 风3 WIND
        {68, 2, 144}, // 0x44 风4 WIND
        {81, 802, 2}, // 0x51 箭1 DRAGON
        {82, 642, 2}, // 0x52 箭2 DRAGON
        {83, 482, 2}, // 0x53 箭3 DRAGON
        {97, 322, 2}, // 0x61 花1 FLOWER
        {98, 162, 2}, // 0x62 花2 FLOWER
        {99, 2, 2}, // 0x63 花3 FLOWER
        {100, 802, 854}, // 0x64 花4 FLOWER
        {101, 642, 854}, // 0x65 花5 FLOWER
        {102, 482, 854}, // 0x66 花6 FLOWER
        {103, 322, 854}, // 0x67 花7 FLOWER
        {104, 162, 854}, // 0x68 花8 FLOWER
    };

    private TaizhouMahjongFaceAtlas() {}

    /** Returns the atlas origin of {@code tileId}, or null when absent. */
    public static int[] frameOf(int tileId) {
        for (int[] frame : FRAMES) {
            if (frame[0] == tileId) {
                return new int[] {frame[1], frame[2]};
            }
        }
        return null;
    }
}
