package com.nanbeiyule.game.mahjong;

/**
 * Frame rects of the original Taizhou mahjong table atlases.
 *
 * <p>Generated by android/tools/extract_original_taizhou_mahjong_table_assets.py
 * from the original CocoStudio plists. Do not edit by hand.
 *
 * <p>Each frame is {@code {atlasX, atlasY, width, height, rotated}}. A rotated
 * frame occupies a {@code height x width} region in the atlas and must be turned
 * back counter-clockwise to obtain the upright {@code width x height} image.
 */
public final class TaizhouMahjongTableAtlas {
    private TaizhouMahjongTableAtlas() {}

    /** Android resource name of the taizhou_mahjong_action_btn atlas bitmap. */
    public static final String ACTION_BTN_RESOURCE = "taizhou_mahjong_action_btn";

    /** taizhou_mahjong_action_btn atlas bitmap size. */
    public static final int ACTION_BTN_WIDTH = 2027;

    public static final int ACTION_BTN_HEIGHT = 204;

    /** Frame names of taizhou_mahjong_action_btn, aligned with ACTION_BTN_FRAMES. */
    public static final String[] ACTION_BTN_NAMES = {
        "action_cancle.png",
        "action_chi.png",
        "action_combs_bg.png",
        "action_gang.png",
        "action_hu.png",
        "action_hua_hu.png",
        "action_pass.png",
        "action_peng.png",
        "action_sha_zhu.png",
        "action_ting.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_action_btn. */
    public static final int[][] ACTION_BTN_FRAMES = {
        {1618, 2, 150, 150, 0},
        {1416, 2, 200, 200, 0},
        {1770, 2, 255, 103, 0},
        {1214, 2, 200, 200, 0},
        {1012, 2, 200, 200, 0},
        {810, 2, 200, 200, 0},
        {608, 2, 200, 200, 0},
        {406, 2, 200, 200, 0},
        {204, 2, 200, 200, 0},
        {2, 2, 200, 200, 0},
    };

    /** Android resource name of the taizhou_mahjong_back atlas bitmap. */
    public static final String BACK_RESOURCE = "taizhou_mahjong_back";

    /** taizhou_mahjong_back atlas bitmap size. */
    public static final int BACK_WIDTH = 2020;

    public static final int BACK_HEIGHT = 167;

    /** Frame names of taizhou_mahjong_back, aligned with BACK_FRAMES. */
    public static final String[] BACK_NAMES = {
        "mah_back_1_0.png",
        "mah_back_1_2.png",
        "mah_back_1_3.png",
        "mah_back_2_0.png",
        "mah_back_2_1.png",
        "mah_back_2_2.png",
        "mah_back_2_3.png",
        "mah_back_3_0.png",
        "mah_back_3_2.png",
        "mah_back_3_3.png",
        "mah_back_4_0.png",
        "mah_back_4_1.png",
        "mah_back_4_2.png",
        "mah_back_4_3.png",
        "mah_img_sign.png",
        "mah_img_surplus.png",
        "mah_img_zhuang_0.png",
        "mah_img_zhuang_1.png",
        "mah_img_zhuang_2.png",
        "mah_shape_1.png",
        "mah_shape_2.png",
        "mah_shape_3.png",
        "mah_shape_4.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_back. */
    public static final int[][] BACK_FRAMES = {
        {1583, 88, 77, 192, 1},
        {364, 2, 177, 141, 0},
        {185, 2, 177, 141, 0},
        {543, 2, 138, 193, 1},
        {932, 2, 138, 192, 1},
        {1126, 2, 138, 191, 1},
        {738, 2, 138, 192, 1},
        {1827, 2, 77, 191, 1},
        {364, 2, 177, 141, 0},
        {185, 2, 177, 141, 0},
        {543, 2, 138, 193, 1},
        {932, 2, 138, 192, 1},
        {1126, 2, 138, 191, 1},
        {738, 2, 138, 192, 1},
        {1960, 81, 52, 39, 0},
        {1500, 2, 104, 34, 1},
        {1769, 2, 81, 56, 1},
        {1711, 2, 81, 56, 1},
        {1500, 108, 81, 56, 0},
        {1777, 85, 79, 181, 1},
        {2, 2, 141, 181, 1},
        {1319, 2, 179, 131, 0},
        {1536, 2, 173, 84, 0},
    };

    /** Android resource name of the taizhou_mahjong_back_2 atlas bitmap. */
    public static final String BACK_2_RESOURCE = "taizhou_mahjong_back_2";

    /** taizhou_mahjong_back_2 atlas bitmap size. */
    public static final int BACK_2_WIDTH = 1006;

    public static final int BACK_2_HEIGHT = 197;

    /** Frame names of taizhou_mahjong_back_2, aligned with BACK_2_FRAMES. */
    public static final String[] BACK_2_NAMES = {
        "mah_back_2_1_0.png",
        "mah_back_2_1_2.png",
        "mah_back_2_1_3.png",
        "mah_back_2_2_0.png",
        "mah_back_2_2_1.png",
        "mah_back_2_2_2.png",
        "mah_back_2_2_3.png",
        "mah_back_2_3_0.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_back_2. */
    public static final int[][] BACK_2_FRAMES = {
        {422, 2, 77, 192, 0},
        {863, 2, 177, 141, 1},
        {720, 2, 177, 141, 1},
        {2, 2, 138, 193, 0},
        {282, 2, 138, 192, 0},
        {501, 2, 138, 191, 0},
        {142, 2, 138, 192, 0},
        {641, 2, 77, 191, 0},
    };

    /** Android resource name of the taizhou_mahjong_icon atlas bitmap. */
    public static final String ICON_RESOURCE = "taizhou_mahjong_icon";

    /** taizhou_mahjong_icon atlas bitmap size. */
    public static final int ICON_WIDTH = 256;

    public static final int ICON_HEIGHT = 256;

    /** Frame names of taizhou_mahjong_icon, aligned with ICON_FRAMES. */
    public static final String[] ICON_NAMES = {
        "mahlayer_mah_any.png",
        "mahlayer_mah_face_flower.png",
        "mahlayer_mah_face_joker_circle.png",
        "mahlayer_mah_face_joker_square.png",
        "mahlayer_mah_img_bao.png",
        "mahlayer_mah_img_sign.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_icon. */
    public static final int[][] ICON_FRAMES = {
        {2, 2, 64, 134, 0},
        {151, 2, 81, 84, 1},
        {68, 2, 81, 85, 0},
        {2, 138, 81, 85, 0},
        {151, 85, 67, 70, 1},
        {68, 89, 52, 39, 0},
    };

    /** Android resource name of the taizhou_mahjong_flower_number atlas bitmap. */
    public static final String FLOWER_NUMBER_RESOURCE = "taizhou_mahjong_flower_number";

    /** taizhou_mahjong_flower_number atlas bitmap size. */
    public static final int FLOWER_NUMBER_WIDTH = 128;

    public static final int FLOWER_NUMBER_HEIGHT = 128;

    /** Frame names of taizhou_mahjong_flower_number, aligned with FLOWER_NUMBER_FRAMES. */
    public static final String[] FLOWER_NUMBER_NAMES = {
        "black_1.png",
        "black_2.png",
        "black_3.png",
        "black_4.png",
        "red_1.png",
        "red_2.png",
        "red_3.png",
        "red_4.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_flower_number. */
    public static final int[][] FLOWER_NUMBER_FRAMES = {
        {16, 82, 12, 38, 0},
        {55, 2, 23, 37, 1},
        {2, 42, 22, 38, 0},
        {26, 41, 26, 37, 0},
        {2, 82, 12, 38, 0},
        {30, 80, 23, 37, 0},
        {2, 2, 22, 38, 0},
        {26, 2, 26, 37, 0},
    };

    /** Android resource name of the taizhou_mahjong_round_wind atlas bitmap. */
    public static final String ROUND_WIND_RESOURCE = "taizhou_mahjong_round_wind";

    /** taizhou_mahjong_round_wind atlas bitmap size. */
    public static final int ROUND_WIND_WIDTH = 128;

    public static final int ROUND_WIND_HEIGHT = 256;

    /** Frame names of taizhou_mahjong_round_wind, aligned with ROUND_WIND_FRAMES. */
    public static final String[] ROUND_WIND_NAMES = {
        "img_quanfeng_0.png",
        "img_quanfeng_1.png",
        "img_quanfeng_2.png",
        "img_quanfeng_3.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_round_wind. */
    public static final int[][] ROUND_WIND_FRAMES = {
        {2, 84, 115, 39, 0},
        {2, 43, 115, 39, 0},
        {2, 125, 114, 40, 0},
        {2, 2, 115, 39, 0},
    };

    /** Android resource name of the taizhou_mahjong_action_tip atlas bitmap. */
    public static final String ACTION_TIP_RESOURCE = "taizhou_mahjong_action_tip";

    /** taizhou_mahjong_action_tip atlas bitmap size. */
    public static final int ACTION_TIP_WIDTH = 512;

    public static final int ACTION_TIP_HEIGHT = 512;

    /** Frame names of taizhou_mahjong_action_tip, aligned with ACTION_TIP_FRAMES. */
    public static final String[] ACTION_TIP_NAMES = {
        "act_buhua.png",
        "act_chi.png",
        "act_gang.png",
        "act_peng.png",
        "eff_hupai.png",
        "eff_piaocai.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_action_tip. */
    public static final int[][] ACTION_TIP_FRAMES = {
        {2, 2, 419, 129, 0},
        {2, 387, 146, 121, 0},
        {293, 133, 180, 119, 0},
        {150, 342, 154, 119, 1},
        {2, 133, 252, 131, 1},
        {135, 133, 207, 156, 1},
    };

    /** Android resource name of the taizhou_mahjong_table_info atlas bitmap. */
    public static final String TABLE_INFO_RESOURCE = "taizhou_mahjong_table_info";

    /** taizhou_mahjong_table_info atlas bitmap size. */
    public static final int TABLE_INFO_WIDTH = 84;

    public static final int TABLE_INFO_HEIGHT = 945;

    /** Frame names of taizhou_mahjong_table_info, aligned with TABLE_INFO_FRAMES. */
    public static final String[] TABLE_INFO_NAMES = {
        "mah_img_surplus.png",
        "tz_chengbao.png",
        "tz_maidi.png",
        "tz_over_lazi.png",
        "tz_settle_icon_1.png",
        "tz_settle_icon_2.png",
        "tz_settle_icon_3.png",
        "tz_settle_icon_4.png",
        "tz_settle_icon_5.png",
        "tz_settle_icon_9.png",
        "tz_shengPai.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_table_info. */
    public static final int[][] TABLE_INFO_FRAMES = {
        {46, 740, 104, 34, 1},
        {46, 846, 36, 36, 0},
        {51, 884, 28, 29, 1},
        {2, 892, 47, 51, 0},
        {2, 617, 121, 80, 1},
        {2, 494, 121, 80, 1},
        {2, 371, 121, 80, 1},
        {2, 248, 121, 80, 1},
        {2, 125, 121, 80, 1},
        {2, 2, 121, 80, 1},
        {2, 740, 150, 42, 1},
    };

    /** Android resource name of the taizhou_mahjong_tan_btn atlas bitmap. */
    public static final String TAN_BTN_RESOURCE = "taizhou_mahjong_tan_btn";

    /** taizhou_mahjong_tan_btn atlas bitmap size. */
    public static final int TAN_BTN_WIDTH = 512;

    public static final int TAN_BTN_HEIGHT = 1024;

    /** Frame names of taizhou_mahjong_tan_btn, aligned with TAN_BTN_FRAMES. */
    public static final String[] TAN_BTN_NAMES = {
        "action_pass.png",
        "tz_niu_flag.png",
        "tz_tanBtn1.png",
        "tz_tanBtn2.png",
        "tz_tanBtn3.png",
        "tz_tanBtn4.png",
        "tz_wait_maidi.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_tan_btn. */
    public static final int[][] TAN_BTN_FRAMES = {
        {204, 608, 200, 200, 0},
        {98, 2, 28, 29, 1},
        {204, 406, 200, 200, 0},
        {204, 204, 200, 200, 0},
        {204, 2, 200, 200, 0},
        {2, 795, 200, 200, 0},
        {2, 2, 791, 94, 1},
    };

    /** Android resource name of the taizhou_mahjong_zhua_gang_tou atlas bitmap. */
    public static final String ZHUA_GANG_TOU_RESOURCE = "taizhou_mahjong_zhua_gang_tou";

    /** taizhou_mahjong_zhua_gang_tou atlas bitmap size. */
    public static final int ZHUA_GANG_TOU_WIDTH = 1544;

    public static final int ZHUA_GANG_TOU_HEIGHT = 322;

    /** Frame names of taizhou_mahjong_zhua_gang_tou, aligned with ZHUA_GANG_TOU_FRAMES. */
    public static final String[] ZHUA_GANG_TOU_NAMES = {
        "tz_fanGangTou.png",
        "tz_fang.png",
        "tz_mahEveryBoxBg.png",
        "tz_zhuaChong.png",
        "tz_zhuaGangTou.png",
        "tz_zhuaGangTouBg.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_zhua_gang_tou. */
    public static final int[][] ZHUA_GANG_TOU_FRAMES = {
        {1068, 157, 310, 105, 0},
        {1381, 50, 77, 80, 1},
        {2, 2, 1540, 46, 0},
        {961, 50, 204, 105, 1},
        {1068, 50, 311, 105, 0},
        {2, 50, 957, 270, 0},
    };

    /** Android resource name of the taizhou_mahjong_early_start atlas bitmap. */
    public static final String EARLY_START_RESOURCE = "taizhou_mahjong_early_start";

    /** taizhou_mahjong_early_start atlas bitmap size. */
    public static final int EARLY_START_WIDTH = 206;

    public static final int EARLY_START_HEIGHT = 444;

    /** Frame names of taizhou_mahjong_early_start, aligned with EARLY_START_FRAMES. */
    public static final String[] EARLY_START_NAMES = {
        "tz_bg_early_start_tip.png",
        "tz_btn_early_start.png",
        "tz_early_start_title.png",
    };

    /** {atlasX, atlasY, width, height, rotated} for taizhou_mahjong_early_start. */
    public static final int[][] EARLY_START_FRAMES = {
        {2, 2, 195, 92, 0},
        {2, 96, 346, 136, 1},
        {140, 96, 216, 64, 1},
    };

    /** Returns the frame index of {@code name} in {@code names}, or -1. */
    public static int indexOf(String[] names, String name) {
        for (int index = 0; index < names.length; index++) {
            if (names[index].equals(name)) {
                return index;
            }
        }
        return -1;
    }
}
