package com.nanbeiyule.game.mahjong;

/**
 * Frame rects of the additional original Taizhou mahjong atlases.
 *
 * <p>Generated by android/tools/extract_original_taizhou_mahjong_extra_assets.py
 * from the original CocoStudio plists. Do not edit by hand.
 *
 * <p>Each frame row is {@code {atlasX, atlasY, width, height, rotated, offsetX,
 * offsetY, sourceWidth, sourceHeight}}. A rotated frame occupies a
 * {@code height x width} region in the atlas and must be turned back
 * counter-clockwise to obtain the upright {@code width x height} image.
 * Trimmed frames sit at {@code ((sourceWidth-width)/2+offsetX,
 * (sourceHeight-height)/2-offsetY)} of their logical source canvas.
 */
public final class TaizhouMahjongExtraAtlas {
    private TaizhouMahjongExtraAtlas() {}

    /** Android resource name of the taizhou_mahjong_can_hu_tip whole-atlas bitmap. */
    public static final String TAIZHOU_MAHJONG_CAN_HU_TIP_RESOURCE = "taizhou_mahjong_can_hu_tip_atlas";

    /** taizhou_mahjong_can_hu_tip atlas bitmap size. */
    public static final int TAIZHOU_MAHJONG_CAN_HU_TIP_WIDTH = 495;

    public static final int TAIZHOU_MAHJONG_CAN_HU_TIP_HEIGHT = 342;

    /** Frame names of taizhou_mahjong_can_hu_tip, aligned with TAIZHOU_MAHJONG_CAN_HU_TIP_FRAMES. */
    public static final String[] TAIZHOU_MAHJONG_CAN_HU_TIP_NAMES = {
        "can_hu_bg.png",
        "division_line.png",
        "hu.png",
    };

    /** Frame rows of taizhou_mahjong_can_hu_tip; see class javadoc for the layout. */
    public static final int[][] TAIZHOU_MAHJONG_CAN_HU_TIP_FRAMES = {
        {393, 2, 100, 100, 0, 0, 0, 100, 100},
        {393, 104, 2, 192, 0, 0, 0, 2, 192},
        {2, 2, 389, 338, 0, 0, 0, 389, 338},
    };

    /** Android resource name of the taizhou_mahjong_game_layer2 whole-atlas bitmap. */
    public static final String TAIZHOU_MAHJONG_GAME_LAYER2_RESOURCE = "taizhou_mahjong_game_layer2_atlas";

    /** taizhou_mahjong_game_layer2 atlas bitmap size. */
    public static final int TAIZHOU_MAHJONG_GAME_LAYER2_WIDTH = 78;

    public static final int TAIZHOU_MAHJONG_GAME_LAYER2_HEIGHT = 93;

    /** Frame names of taizhou_mahjong_game_layer2, aligned with TAIZHOU_MAHJONG_GAME_LAYER2_FRAMES. */
    public static final String[] TAIZHOU_MAHJONG_GAME_LAYER2_NAMES = {
        "head_trust.png",
    };

    /** Frame rows of taizhou_mahjong_game_layer2; see class javadoc for the layout. */
    public static final int[][] TAIZHOU_MAHJONG_GAME_LAYER2_FRAMES = {
        {2, 2, 74, 89, 0, 0, 0, 74, 89},
    };

    /** Android resource name of the taizhou_mahjong_center_dis whole-atlas bitmap. */
    public static final String TAIZHOU_MAHJONG_CENTER_DIS_RESOURCE = "taizhou_mahjong_center_dis_atlas";

    /** taizhou_mahjong_center_dis atlas bitmap size. */
    public static final int TAIZHOU_MAHJONG_CENTER_DIS_WIDTH = 256;

    public static final int TAIZHOU_MAHJONG_CENTER_DIS_HEIGHT = 512;

    /** Frame names of taizhou_mahjong_center_dis, aligned with TAIZHOU_MAHJONG_CENTER_DIS_FRAMES. */
    public static final String[] TAIZHOU_MAHJONG_CENTER_DIS_NAMES = {
        "xgsj_Iimg_B.png",
        "xgsj_Iimg_B2.png",
        "xgsj_Iimg_D.png",
        "xgsj_Iimg_D2.png",
        "xgsj_Iimg_X.png",
        "xgsj_Iimg_X2.png",
        "xgsj_Iimg_n.png",
        "xgsj_Iimg_n2.png",
        "xgsj_Img_di.png",
        "xgsj_Img_lb.png",
        "xgsj_Img_ld.png",
        "xgsj_Img_lx.png",
        "xgsj_iMG_ln.png",
    };

    /** Frame rows of taizhou_mahjong_center_dis; see class javadoc for the layout. */
    public static final int[][] TAIZHOU_MAHJONG_CENTER_DIS_FRAMES = {
        {112, 305, 40, 38, 1, 0, 0, 54, 56},
        {50, 443, 54, 52, 1, 0, 0, 54, 56},
        {102, 385, 32, 42, 0, 0, 0, 54, 56},
        {2, 443, 46, 56, 0, 0, 0, 54, 56},
        {72, 349, 34, 36, 1, 0, 1, 54, 56},
        {54, 385, 46, 50, 0, 0, 1, 54, 56},
        {72, 305, 38, 42, 0, 0, 0, 54, 56},
        {2, 385, 50, 56, 0, 0, 0, 54, 56},
        {2, 2, 231, 235, 1, 0, -5, 267, 267},
        {82, 235, 78, 68, 0, 0, 1, 78, 78},
        {2, 305, 68, 78, 0, -1, 0, 78, 78},
        {162, 235, 68, 78, 1, -1, 0, 78, 78},
        {2, 235, 78, 68, 0, 0, 1, 78, 78},
    };

    /** Android resource name of the taizhou_mahjong_buy_code whole-atlas bitmap. */
    public static final String TAIZHOU_MAHJONG_BUY_CODE_RESOURCE = "taizhou_mahjong_buy_code_atlas";

    /** taizhou_mahjong_buy_code atlas bitmap size. */
    public static final int TAIZHOU_MAHJONG_BUY_CODE_WIDTH = 512;

    public static final int TAIZHOU_MAHJONG_BUY_CODE_HEIGHT = 2048;

    /** Frame names of taizhou_mahjong_buy_code, aligned with TAIZHOU_MAHJONG_BUY_CODE_FRAMES. */
    public static final String[] TAIZHOU_MAHJONG_BUY_CODE_NAMES = {
        "ma_beifeng.png",
        "ma_boxbg.png",
        "ma_dongfeng.png",
        "ma_icon_bei.png",
        "ma_icon_dong.png",
        "ma_icon_nan.png",
        "ma_icon_xi.png",
        "ma_nanfeng.png",
        "ma_pass.png",
        "ma_txt.png",
        "ma_txtX.png",
        "ma_txtbg.png",
        "ma_xifeng.png",
    };

    /** Frame rows of taizhou_mahjong_buy_code; see class javadoc for the layout. */
    public static final int[][] TAIZHOU_MAHJONG_BUY_CODE_FRAMES = {
        {196, 493, 227, 82, 1, 0, 0, 227, 82},
        {2, 2, 1753, 90, 1, 0, 0, 1753, 90},
        {231, 1903, 227, 83, 0, 0, 0, 227, 83},
        {196, 2, 144, 260, 0, 0, 0, 144, 260},
        {94, 1575, 144, 260, 1, 0, 0, 144, 260},
        {94, 1313, 144, 260, 0, 0, 0, 144, 260},
        {2, 1757, 144, 260, 1, 0, 0, 144, 260},
        {196, 264, 227, 82, 1, 0, 0, 227, 82},
        {2, 1903, 227, 97, 0, 0, 0, 227, 97},
        {264, 1721, 157, 93, 0, 0, 0, 157, 93},
        {196, 722, 59, 93, 0, 0, 0, 59, 93},
        {94, 2, 1309, 100, 1, 0, 0, 1309, 100},
        {264, 1816, 227, 82, 0, 0, 0, 227, 82},
    };

    /** Android resource name of the taizhou_mahjong_dead_area whole-atlas bitmap. */
    public static final String TAIZHOU_MAHJONG_DEAD_AREA_RESOURCE = "taizhou_mahjong_dead_area_atlas";

    /** taizhou_mahjong_dead_area atlas bitmap size. */
    public static final int TAIZHOU_MAHJONG_DEAD_AREA_WIDTH = 480;

    public static final int TAIZHOU_MAHJONG_DEAD_AREA_HEIGHT = 228;

    /** Frame names of taizhou_mahjong_dead_area, aligned with TAIZHOU_MAHJONG_DEAD_AREA_FRAMES. */
    public static final String[] TAIZHOU_MAHJONG_DEAD_AREA_NAMES = {
        "area_btn_check.png",
        "area_btn_close.png",
        "area_img_bg.png",
    };

    /** Frame rows of taizhou_mahjong_dead_area; see class javadoc for the layout. */
    public static final int[][] TAIZHOU_MAHJONG_DEAD_AREA_FRAMES = {
        {181, 2, 297, 121, 0, 0, 0, 297, 121},
        {181, 125, 101, 101, 0, 0, 0, 101, 101},
        {2, 2, 184, 177, 1, 0, 0, 184, 177},
    };

    /** Returns the frame index of {@code name} in {@code names}, or -1. */
    public static int indexOf(String[] names, String name) {
        for (int index = 0; index < names.length; index++) {
            if (names[index].equals(name)) {
                return index;
            }
        }
        return -1;
    }
}
