package com.nanbeiyule.game.gameplay;

import com.nanbeiyule.game.mahjong.TaizhouMahjongPlayPermission;
import com.nanbeiyule.game.mahjong.TaizhouMahjongVisibleRound;
import com.nanbeiyule.game.mahjong.TaizhouSettleState;
import com.nanbeiyule.game.mahjong.TaizhouDiceState;
import com.nanbeiyule.game.mahjong.TaizhouMultipleState;
import com.nanbeiyule.game.mahjong.TaizhouTotalResultState;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public record GameplayTableState(
        String sessionId,
        String roomNumber,
        long gameId,
        int roomMode,
        String roomVenue,
        GameplayPhase phase,
        int roundNumber,
        long revision,
        int eventOrder,
        int chairCount,
        int maxPlayCount,
        String gameRuleDisplay,
        boolean autoReady,
        int mySeat,
        List<GameplaySeat> seats,
        Optional<TaizhouMahjongVisibleRound> visibleRound,
        Optional<TaizhouMahjongPlayPermission> playPermission,
        Optional<TaizhouSettleState> settlement,
        Optional<TaizhouMultipleState> multipleChoice,
        Integer activeSeat,
        Integer clockRemainingSeconds,
        int remainingWallCount,
        String updatedAt,
        Optional<GameplayActionOffer> actionOffer,
        List<GameplayMeld> melds,
        List<GameplaySeatFlowers> flowers,
        Optional<GameplayActionTip> actionTip,
        Optional<GameplayTingInfo> tingInfo,
        Integer shengPaiCount,
        Integer leftBankerCount,
        Optional<TaizhouDiceState> diceRoll,
        Optional<TaizhouTotalResultState> totalResult,
        Map<Integer, Boolean> chengBaoFlagsBySeat) {
    public GameplayTableState(
            String sessionId,
            String roomNumber,
            long gameId,
            GameplayPhase phase,
            int roundNumber,
            long revision,
            int eventOrder,
            int chairCount,
            int maxPlayCount,
            String gameRuleDisplay,
            boolean autoReady,
            int mySeat,
            List<GameplaySeat> seats,
            Optional<TaizhouMahjongVisibleRound> visibleRound,
            Optional<TaizhouMahjongPlayPermission> playPermission,
            Optional<TaizhouSettleState> settlement,
            Optional<TaizhouMultipleState> multipleChoice,
            Integer activeSeat,
            Integer clockRemainingSeconds,
            int remainingWallCount,
            String updatedAt,
            Optional<GameplayActionOffer> actionOffer,
            List<GameplayMeld> melds,
            List<GameplaySeatFlowers> flowers,
            Optional<GameplayActionTip> actionTip,
            Optional<GameplayTingInfo> tingInfo,
            Integer shengPaiCount,
            Integer leftBankerCount,
            Optional<TaizhouDiceState> diceRoll,
            Optional<TaizhouTotalResultState> totalResult,
            Map<Integer, Boolean> chengBaoFlagsBySeat) {
        this(
                sessionId,
                roomNumber,
                gameId,
                0,
                "",
                phase,
                roundNumber,
                revision,
                eventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                visibleRound,
                playPermission,
                settlement,
                multipleChoice,
                activeSeat,
                clockRemainingSeconds,
                remainingWallCount,
                updatedAt,
                actionOffer,
                melds,
                flowers,
                actionTip,
                tingInfo,
                shengPaiCount,
                leftBankerCount,
                diceRoll,
                totalResult,
                chengBaoFlagsBySeat);
    }

    public GameplayTableState(
            String sessionId,
            String roomNumber,
            long gameId,
            GameplayPhase phase,
            int roundNumber,
            long revision,
            int eventOrder,
            int chairCount,
            int maxPlayCount,
            String gameRuleDisplay,
            boolean autoReady,
            int mySeat,
            List<GameplaySeat> seats,
            Optional<TaizhouMahjongVisibleRound> visibleRound,
            Optional<TaizhouMahjongPlayPermission> playPermission,
            Optional<TaizhouSettleState> settlement,
            Optional<TaizhouMultipleState> multipleChoice,
            Integer activeSeat,
            Integer clockRemainingSeconds,
            int remainingWallCount,
            String updatedAt,
            Optional<GameplayActionOffer> actionOffer,
            List<GameplayMeld> melds,
            List<GameplaySeatFlowers> flowers,
            Optional<GameplayActionTip> actionTip,
            Optional<GameplayTingInfo> tingInfo,
            Integer shengPaiCount,
            Integer leftBankerCount,
            Optional<TaizhouDiceState> diceRoll,
            Optional<TaizhouTotalResultState> totalResult) {
        this(
                sessionId,
                roomNumber,
                gameId,
                0,
                "",
                phase,
                roundNumber,
                revision,
                eventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                visibleRound,
                playPermission,
                settlement,
                multipleChoice,
                activeSeat,
                clockRemainingSeconds,
                remainingWallCount,
                updatedAt,
                actionOffer,
                melds,
                flowers,
                actionTip,
                tingInfo,
                shengPaiCount,
                leftBankerCount,
                diceRoll,
                totalResult,
                Map.of());
    }

    public GameplayTableState(
            String sessionId,
            String roomNumber,
            long gameId,
            GameplayPhase phase,
            int roundNumber,
            long revision,
            int eventOrder,
            int chairCount,
            int maxPlayCount,
            String gameRuleDisplay,
            boolean autoReady,
            int mySeat,
            List<GameplaySeat> seats,
            Optional<TaizhouMahjongVisibleRound> visibleRound,
            Optional<TaizhouMahjongPlayPermission> playPermission,
            Optional<TaizhouSettleState> settlement,
            Optional<TaizhouMultipleState> multipleChoice,
            Integer activeSeat,
            int remainingWallCount,
            String updatedAt,
            Optional<GameplayActionOffer> actionOffer,
            List<GameplayMeld> melds,
            List<GameplaySeatFlowers> flowers,
            Optional<GameplayActionTip> actionTip,
            Optional<GameplayTingInfo> tingInfo,
            Integer shengPaiCount,
            Integer leftBankerCount) {
        this(
                sessionId,
                roomNumber,
                gameId,
                0,
                "",
                phase,
                roundNumber,
                revision,
                eventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                visibleRound,
                playPermission,
                settlement,
                multipleChoice,
                activeSeat,
                null,
                remainingWallCount,
                updatedAt,
                actionOffer,
                melds,
                flowers,
                actionTip,
                tingInfo,
                shengPaiCount,
                leftBankerCount,
                Optional.empty(),
                Optional.empty(),
                Map.of());
    }
    public GameplayTableState(
            String sessionId,
            String roomNumber,
            long gameId,
            GameplayPhase phase,
            int roundNumber,
            long revision,
            int eventOrder,
            int chairCount,
            int maxPlayCount,
            String gameRuleDisplay,
            boolean autoReady,
            int mySeat,
            List<GameplaySeat> seats,
            Optional<TaizhouMahjongVisibleRound> visibleRound,
            Optional<TaizhouMahjongPlayPermission> playPermission,
            Optional<TaizhouSettleState> settlement,
            String updatedAt) {
        this(
                sessionId,
                roomNumber,
                gameId,
                0,
                "",
                phase,
                roundNumber,
                revision,
                eventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                visibleRound,
                playPermission,
                settlement,
                Optional.empty(),
                null,
                null,
                -1,
                updatedAt,
                Optional.empty(),
                List.of(),
                List.of(),
                Optional.empty(),
                Optional.empty(),
                null,
                null,
                Optional.empty(),
                Optional.empty(),
                Map.of());
    }
    public GameplayTableState(
            String sessionId,
            String roomNumber,
            long gameId,
            GameplayPhase phase,
            int roundNumber,
            long revision,
            int eventOrder,
            int chairCount,
            int maxPlayCount,
            String gameRuleDisplay,
            boolean autoReady,
            int mySeat,
            List<GameplaySeat> seats,
            String updatedAt) {
        this(
                sessionId,
                roomNumber,
                gameId,
                0,
                "",
                phase,
                roundNumber,
                revision,
                eventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                Optional.empty(),
                Optional.empty(),
                Optional.empty(),
                Optional.empty(),
                null,
                null,
                -1,
                updatedAt,
                Optional.empty(),
                List.of(),
                List.of(),
                Optional.empty(),
                Optional.empty(),
                null,
                null,
                Optional.empty(),
                Optional.empty(),
                Map.of());
    }
    public GameplayTableState {
        seats = List.copyOf(seats);
        roomVenue = roomVenue == null ? "" : roomVenue;
        visibleRound = visibleRound == null ? Optional.empty() : visibleRound;
        playPermission = playPermission == null ? Optional.empty() : playPermission;
        settlement = settlement == null ? Optional.empty() : settlement;
        multipleChoice = multipleChoice == null ? Optional.empty() : multipleChoice;
        actionOffer = actionOffer == null ? Optional.empty() : actionOffer;
        melds = melds == null ? List.of() : List.copyOf(melds);
        flowers = flowers == null ? List.of() : List.copyOf(flowers);
        actionTip = actionTip == null ? Optional.empty() : actionTip;
        tingInfo = tingInfo == null ? Optional.empty() : tingInfo;
        diceRoll = diceRoll == null ? Optional.empty() : diceRoll;
        totalResult = totalResult == null ? Optional.empty() : totalResult;
        chengBaoFlagsBySeat =
                chengBaoFlagsBySeat == null ? Map.of() : Map.copyOf(chengBaoFlagsBySeat);
        if (shengPaiCount != null && shengPaiCount < 0) {
            throw new IllegalArgumentException("shengPaiCount must be non-negative");
        }
        if (leftBankerCount != null && leftBankerCount < 0) {
            throw new IllegalArgumentException("leftBankerCount must be non-negative");
        }
        if (clockRemainingSeconds != null && clockRemainingSeconds < 0) {
            throw new IllegalArgumentException("clockRemainingSeconds must be non-negative");
        }
        if (activeSeat != null && (activeSeat <= 0 || activeSeat > chairCount)) {
            throw new IllegalArgumentException("activeSeat is outside chairCount");
        }
        if (remainingWallCount < -1) {
            throw new IllegalArgumentException("remainingWallCount must be -1 or non-negative");
        }
        if (diceRoll.isPresent() && diceRoll.get().seatNumber() > chairCount) {
            throw new IllegalArgumentException("dice seat is outside chairCount");
        }
        for (int seat : chengBaoFlagsBySeat.keySet()) {
            if (seat <= 0 || seat > chairCount) {
                throw new IllegalArgumentException("chengBao flag seat is outside chairCount");
            }
        }
    }
    GameplayTableState withEvent(
            long nextRevision,
            int nextEventOrder,
            List<GameplaySeat> nextSeats) {
        return new GameplayTableState(
                sessionId,
                roomNumber,
                gameId,
                roomMode,
                roomVenue,
                phase,
                roundNumber,
                nextRevision,
                nextEventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                nextSeats,
                visibleRound,
                playPermission,
                settlement,
                multipleChoice,
                activeSeat,
                clockRemainingSeconds,
                remainingWallCount,
                updatedAt,
                actionOffer,
                melds,
                flowers,
                actionTip,
                tingInfo,
                shengPaiCount,
                leftBankerCount,
                diceRoll,
                totalResult,
                chengBaoFlagsBySeat);
    }
    GameplayTableState withCursorMetadata(
            long nextRevision,
            int nextEventOrder,
            Integer nextActiveSeat,
            Integer nextClockRemainingSeconds,
            int nextRemainingWallCount) {
        return new GameplayTableState(
                sessionId,
                roomNumber,
                gameId,
                roomMode,
                roomVenue,
                phase,
                roundNumber,
                nextRevision,
                nextEventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                visibleRound,
                playPermission,
                settlement,
                multipleChoice,
                nextActiveSeat,
                nextClockRemainingSeconds,
                nextRemainingWallCount,
                updatedAt,
                actionOffer,
                melds,
                flowers,
                actionTip,
                tingInfo,
                shengPaiCount,
                leftBankerCount,
                diceRoll,
                totalResult,
                chengBaoFlagsBySeat);
    }
    GameplayTableState withPhaseAndRoundState(
            long nextRevision,
            int nextEventOrder,
            GameplayPhase nextPhase,
            int nextRoundNumber,
            Optional<TaizhouMahjongVisibleRound> nextVisibleRound,
            Optional<TaizhouMahjongPlayPermission> nextPlayPermission,
            Optional<TaizhouSettleState> nextSettlement,
            Optional<TaizhouMultipleState> nextMultipleChoice,
            Integer nextActiveSeat,
            Integer nextClockRemainingSeconds,
            int nextRemainingWallCount) {
        return new GameplayTableState(
                sessionId,
                roomNumber,
                gameId,
                roomMode,
                roomVenue,
                nextPhase,
                nextRoundNumber,
                nextRevision,
                nextEventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                nextVisibleRound,
                nextPlayPermission,
                nextSettlement,
                nextMultipleChoice,
                nextActiveSeat,
                nextClockRemainingSeconds,
                nextRemainingWallCount,
                updatedAt,
                actionOffer,
                melds,
                flowers,
                actionTip,
                tingInfo,
                shengPaiCount,
                leftBankerCount,
                diceRoll,
                totalResult,
                chengBaoFlagsBySeat);
    }
    GameplayTableState withActionLayer(
            long nextRevision,
            int nextEventOrder,
            Optional<GameplayActionOffer> nextActionOffer,
            List<GameplayMeld> nextMelds,
            List<GameplaySeatFlowers> nextFlowers,
            Optional<GameplayActionTip> nextActionTip) {
        return new GameplayTableState(
                sessionId,
                roomNumber,
                gameId,
                roomMode,
                roomVenue,
                phase,
                roundNumber,
                nextRevision,
                nextEventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                visibleRound,
                playPermission,
                settlement,
                multipleChoice,
                activeSeat,
                clockRemainingSeconds,
                remainingWallCount,
                updatedAt,
                nextActionOffer,
                nextMelds,
                nextFlowers,
                nextActionTip,
                tingInfo,
                shengPaiCount,
                leftBankerCount,
                diceRoll,
                totalResult,
                chengBaoFlagsBySeat);
    }
    GameplayTableState withDiceRoll(
            long nextRevision,
            int nextEventOrder,
            Optional<TaizhouDiceState> nextDiceRoll) {
        return new GameplayTableState(
                sessionId,
                roomNumber,
                gameId,
                roomMode,
                roomVenue,
                phase,
                roundNumber,
                nextRevision,
                nextEventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                visibleRound,
                playPermission,
                settlement,
                multipleChoice,
                activeSeat,
                clockRemainingSeconds,
                remainingWallCount,
                updatedAt,
                actionOffer,
                melds,
                flowers,
                actionTip,
                tingInfo,
                shengPaiCount,
                leftBankerCount,
                nextDiceRoll,
                totalResult,
                chengBaoFlagsBySeat);
    }

    /** Replaces the Wave 3 table-info fields (TING_INFO / 生牌数 / 剩庄数). */
    GameplayTableState withTableInfo(
            long nextRevision,
            int nextEventOrder,
            Optional<GameplayTingInfo> nextTingInfo,
            Integer nextShengPaiCount,
            Integer nextLeftBankerCount) {
        return new GameplayTableState(
                sessionId,
                roomNumber,
                gameId,
                roomMode,
                roomVenue,
                phase,
                roundNumber,
                nextRevision,
                nextEventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                visibleRound,
                playPermission,
                settlement,
                multipleChoice,
                activeSeat,
                clockRemainingSeconds,
                remainingWallCount,
                updatedAt,
                actionOffer,
                melds,
                flowers,
                actionTip,
                nextTingInfo,
                nextShengPaiCount,
                nextLeftBankerCount,
                diceRoll,
                totalResult,
                chengBaoFlagsBySeat);
    }

    GameplayTableState withoutPlayPermission(long nextRevision, int nextEventOrder) {
        return new GameplayTableState(
                sessionId,
                roomNumber,
                gameId,
                roomMode,
                roomVenue,
                phase,
                roundNumber,
                nextRevision,
                nextEventOrder,
                chairCount,
                maxPlayCount,
                gameRuleDisplay,
                autoReady,
                mySeat,
                seats,
                visibleRound,
                Optional.empty(),
                settlement,
                multipleChoice,
                activeSeat,
                clockRemainingSeconds,
                remainingWallCount,
                updatedAt,
                actionOffer,
                melds,
                flowers,
                actionTip,
                tingInfo,
                shengPaiCount,
                leftBankerCount,
                diceRoll,
                totalResult,
                chengBaoFlagsBySeat);
    }

}
