package com.nanbeiyule.game.goldroom;

/**
 * Original gold-hall choose-room atlas tables (浙江游戏大厅 1.5.4).
 *
 * <p>Generated by android/tools/extract_original_gold_choose_room_assets.py
 * from the original CocoStudio plists. Do not edit by hand.
 *
 * <p>Each frame is {@code {atlasX, atlasY, width, height, rotated, offsetX,
 * offsetY, sourceWidth, sourceHeight}}. A rotated frame occupies a
 * {@code height x width} region in the atlas and must be turned back
 * counter-clockwise to obtain the upright {@code width x height} image.
 *
 * <p>{@code width x height} is the trimmed rectangle actually stored in the sheet;
 * {@code sourceWidth x sourceHeight} is the untrimmed sprite CocoStudio laid out
 * against, and {@code offset} is the trimmed centre relative to the untrimmed
 * centre in the plist's Y-up axis. Placing a trimmed frame at a CSB node centre
 * therefore needs {@code (+offsetX, -offsetY)} in Android's Y-down design space.
 */
public final class GoldChooseRoomAtlas {
    private GoldChooseRoomAtlas() {}

    /** Android resource name of the gold_choose_room atlas bitmap. */
    public static final String CHOOSE_ROOM_RESOURCE = "gold_choose_room";

    /** gold_choose_room atlas bitmap size. */
    public static final int CHOOSE_ROOM_WIDTH = 2010;

    public static final int CHOOSE_ROOM_HEIGHT = 2042;

    /** Frame names of gold_choose_room, aligned with CHOOSE_ROOM_FRAMES. */
    public static final String[] CHOOSE_ROOM_NAMES = {
        "hall/Image/NewGoldHall/ChooseRoom/Btn_closed.png",
        "hall/Image/NewGoldHall/ChooseRoom/Btn_qwty.png",
        "hall/Image/NewGoldHall/ChooseRoom/Btn_xyy.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_cd_1.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_cd_2.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_cd_3.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_cd_4.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_cd_5.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_cd_6.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_1.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_2.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_3.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_4.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_5.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_rs1.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_rs2.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_rs3.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_rs4.png",
        "hall/Image/NewGoldHall/ChooseRoom/Img_xc_rs5.png",
        "hall/Image/NewGoldHall/ChooseRoom/img_xc_chang_bawang.png",
        "hall/Image/NewGoldHall/ChooseRoom/img_xc_chang_bawang_d.png",
    };

    /** {atlasX, atlasY, width, height, rotated, offsetX, offsetY,
     * sourceWidth, sourceHeight} for gold_choose_room. */
    public static final int[][] CHOOSE_ROOM_FRAMES = {
        {1, 1992, 49, 49, 0, 0, 0, 49, 49},
        {569, 1, 248, 96, 0, 0, 0, 256, 104},
        {569, 99, 248, 96, 0, 0, 0, 256, 104},
        {1, 1832, 429, 78, 0, 0, 0, 429, 78},
        {1, 1912, 429, 78, 0, 0, 0, 429, 78},
        {432, 1832, 429, 78, 0, 0, 0, 429, 78},
        {432, 1912, 429, 78, 0, 0, 0, 429, 78},
        {489, 1, 429, 78, 1, 0, 0, 429, 78},
        {489, 432, 429, 78, 1, 0, 0, 429, 78},
        {1, 684, 486, 572, 0, 0, 0, 486, 572},
        {489, 863, 486, 572, 0, 0, 0, 486, 572},
        {1, 1258, 486, 572, 0, 0, 0, 486, 572},
        {863, 1, 486, 572, 1, 0, 0, 486, 572},
        {1437, 1, 486, 572, 1, 0, 0, 486, 572},
        {52, 1992, 24, 35, 0, 0, 0, 24, 35},
        {78, 1992, 24, 35, 0, 0, 0, 24, 35},
        {104, 1992, 24, 35, 0, 0, 0, 24, 35},
        {130, 1992, 24, 35, 0, 0, 0, 24, 35},
        {156, 1992, 24, 35, 0, 0, 0, 24, 35},
        {1, 1, 486, 681, 0, 0, 0, 486, 681},
        {863, 1437, 438, 525, 0, 0, 14, 486, 572},
    };

    /** Android resource name of the gold_hall_main atlas bitmap. */
    public static final String MAIN_RESOURCE = "gold_hall_main";

    /** gold_hall_main atlas bitmap size. */
    public static final int MAIN_WIDTH = 2039;

    public static final int MAIN_HEIGHT = 2048;

    /** Frame names of gold_hall_main, aligned with MAIN_FRAMES. */
    public static final String[] MAIN_NAMES = {
        "hall/Image/NewGoldHall/Main/Btn_anniu.png",
        "hall/Image/NewGoldHall/Main/Btn_bb.png",
        "hall/Image/NewGoldHall/Main/Btn_fanhui.png",
        "hall/Image/NewGoldHall/Main/Btn_gd2.png",
        "hall/Image/NewGoldHall/Main/Btn_gm.png",
        "hall/Image/NewGoldHall/Main/Btn_kf.png",
        "hall/Image/NewGoldHall/Main/Btn_sz.png",
        "hall/Image/NewGoldHall/Main/Btn_ts.png",
        "hall/Image/NewGoldHall/Main/Btn_wenhao.png",
        "hall/Image/NewGoldHall/Main/IMG_YBK1.png",
        "hall/Image/NewGoldHall/Main/Img_FK.png",
        "hall/Image/NewGoldHall/Main/Img_JB.png",
        "hall/Image/NewGoldHall/Main/Img_JH2.png",
        "hall/Image/NewGoldHall/Main/Img_KS.png",
        "hall/Image/NewGoldHall/Main/Img_LQ.png",
        "hall/Image/NewGoldHall/Main/Img_YBK2.png",
        "hall/Image/NewGoldHall/Main/Img_ZS.png",
        "hall/Image/NewGoldHall/Main/Img_bq1.png",
        "hall/Image/NewGoldHall/Main/Img_bq2.png",
        "hall/Image/NewGoldHall/Main/Img_bq3.png",
        "hall/Image/NewGoldHall/Main/Img_bq3_huo.png",
        "hall/Image/NewGoldHall/Main/Img_cy_zi.png",
        "hall/Image/NewGoldHall/Main/Img_di.png",
        "hall/Image/NewGoldHall/Main/Img_di2.png",
        "hall/Image/NewGoldHall/Main/Img_dl.png",
        "hall/Image/NewGoldHall/Main/Img_empty.png",
        "hall/Image/NewGoldHall/Main/Img_fgx.png",
        "hall/Image/NewGoldHall/Main/Img_gd_title.png",
        "hall/Image/NewGoldHall/Main/Img_huiyuan.png",
        "hall/Image/NewGoldHall/Main/Img_hy.png",
        "hall/Image/NewGoldHall/Main/Img_k1.png",
        "hall/Image/NewGoldHall/Main/Img_k2.png",
        "hall/Image/NewGoldHall/Main/Img_k32.png",
        "hall/Image/NewGoldHall/Main/Img_k33.png",
        "hall/Image/NewGoldHall/Main/Img_k4.png",
        "hall/Image/NewGoldHall/Main/Img_mj.png",
        "hall/Image/NewGoldHall/Main/Img_pai.png",
        "hall/Image/NewGoldHall/Main/Img_pdk_zi.png",
        "hall/Image/NewGoldHall/Main/Img_qb_zi.png",
        "hall/Image/NewGoldHall/Main/Img_ren.png",
        "hall/Image/NewGoldHall/Main/Img_tip_di.png",
        "hall/Image/NewGoldHall/Main/Img_tx_di.png",
        "hall/Image/NewGoldHall/Main/Img_ty1.png",
        "hall/Image/NewGoldHall/Main/Img_ty2.png",
        "hall/Image/NewGoldHall/Main/Img_ty3.png",
        "hall/Image/NewGoldHall/Main/Img_zi_die_1.png",
        "hall/Image/NewGoldHall/Main/Img_zi_die_2.png",
        "hall/Image/NewGoldHall/Main/Img_zi_die_3.png",
        "hall/Image/NewGoldHall/Main/Imh_tips.png",
        "hall/Image/NewGoldHall/Main/Imh_tips_sj.png",
        "hall/Image/NewGoldHall/Main/newgold_progress_1.png",
        "hall/Image/NewGoldHall/Main/newgold_progress_2.png",
        "hall/Image/NewGoldHall/Main/newgold_progress_3.png",
    };

    /** {atlasX, atlasY, width, height, rotated, offsetX, offsetY,
     * sourceWidth, sourceHeight} for gold_hall_main. */
    public static final int[][] MAIN_FRAMES = {
        {389, 1008, 428, 173, 0, 0, 0, 428, 173},
        {1410, 703, 86, 78, 0, 0, 0, 86, 84},
        {1493, 853, 72, 88, 1, 0, -1, 91, 97},
        {389, 1425, 118, 292, 1, 0, 0, 118, 292},
        {853, 774, 82, 83, 0, 0, 0, 82, 83},
        {1324, 703, 81, 84, 1, 0, 0, 86, 84},
        {1410, 783, 80, 81, 1, 0, 0, 86, 84},
        {853, 471, 301, 119, 1, 0, 0, 301, 119},
        {1202, 763, 77, 77, 0, 0, 0, 77, 77},
        {1638, 1, 378, 480, 0, 0, 0, 382, 484},
        {1267, 681, 80, 55, 1, 0, 0, 92, 71},
        {1281, 786, 73, 76, 1, 0, 0, 73, 76},
        {974, 614, 42, 43, 1, 0, 0, 42, 43},
        {736, 383, 287, 86, 0, 0, 0, 289, 88},
        {1202, 842, 71, 71, 0, 1, 0, 92, 71},
        {371, 483, 378, 480, 1, 0, 0, 382, 484},
        {1498, 780, 92, 71, 0, 0, 0, 92, 71},
        {2018, 1, 20, 20, 0, 0, 0, 20, 20},
        {1499, 686, 92, 94, 1, 0, 0, 92, 94},
        {1086, 681, 179, 63, 0, 0, 0, 179, 63},
        {974, 754, 226, 95, 0, 0, 0, 226, 95},
        {974, 471, 33, 72, 0, 0, 0, 33, 72},
        {1120, 539, 242, 58, 0, 0, 0, 242, 58},
        {1086, 383, 125, 38, 1, 0, 0, 125, 38},
        {1364, 539, 150, 95, 0, 0, 0, 150, 95},
        {45, 2046, 1, 1, 0, 0, 0, 1, 1},
        {1, 2046, 1, 42, 1, 0, 0, 1, 42},
        {1086, 607, 247, 72, 0, 0, 0, 247, 72},
        {1335, 636, 162, 65, 0, 0, 0, 162, 65},
        {389, 863, 211, 134, 0, 0, 0, 211, 135},
        {1, 1564, 386, 669, 1, 0, 0, 386, 669},
        {1, 892, 386, 670, 0, 0, 0, 386, 670},
        {371, 159, 382, 222, 0, 0, 0, 382, 222},
        {755, 159, 382, 222, 0, 0, 0, 382, 222},
        {1139, 159, 378, 464, 1, 0, 0, 382, 468},
        {602, 863, 208, 135, 0, 2, 0, 211, 135},
        {812, 863, 182, 132, 0, 15, -2, 211, 135},
        {1086, 510, 32, 95, 0, 0, 0, 32, 95},
        {974, 545, 34, 67, 0, 0, 0, 34, 67},
        {1, 1, 368, 889, 0, 0, 0, 368, 889},
        {1516, 539, 145, 87, 1, 0, 0, 145, 87},
        {371, 1, 1265, 156, 0, 0, 0, 1265, 156},
        {1025, 383, 369, 59, 1, 0, 0, 369, 59},
        {1940, 483, 365, 59, 1, 0, 0, 365, 59},
        {1940, 850, 365, 59, 1, 0, 0, 365, 59},
        {371, 383, 363, 75, 0, 0, 0, 363, 75},
        {1, 1952, 345, 92, 0, 0, 0, 345, 92},
        {348, 1952, 345, 92, 0, 0, 0, 345, 92},
        {1275, 861, 68, 67, 0, 0, 0, 68, 67},
        {2018, 23, 14, 8, 0, 0, 0, 14, 8},
        {672, 1545, 364, 467, 1, 0, 0, 364, 467},
        {1605, 483, 523, 333, 1, 0, 0, 523, 333},
        {389, 1217, 365, 206, 0, 0, 0, 365, 206},
    };

    /** Android resource name of the gold_hall_act_buttons atlas bitmap. */
    public static final String ACT_BUTTON_RESOURCE = "gold_hall_act_buttons";

    /** gold_hall_act_buttons atlas bitmap size. */
    public static final int ACT_BUTTON_WIDTH = 560;

    public static final int ACT_BUTTON_HEIGHT = 1021;

    /** Frame names of gold_hall_act_buttons, aligned with ACT_BUTTON_FRAMES. */
    public static final String[] ACT_BUTTON_NAMES = {
        "hall/Image/NewGoldHall/ActBtns/Btn_xslb.png",
        "hall/Image/NewGoldHall/ActBtns/Icon_hqjb.png",
        "hall/Image/NewGoldHall/ActBtns/Icon_wxfk.png",
        "hall/Image/NewGoldHall/ActBtns/Img_adtz.png",
        "hall/Image/NewGoldHall/ActBtns/Img_icon_adzl.png",
        "hall/Image/NewGoldHall/ActBtns/Img_icon_qsl.png",
        "hall/Image/NewGoldHall/ActBtns/Img_jbyk.png",
        "hall/Image/NewGoldHall/ActBtns/Img_lbhj.png",
        "hall/Image/NewGoldHall/ActBtns/Img_mp.png",
        "hall/Image/NewGoldHall/ActBtns/Img_pc.png",
        "hall/Image/NewGoldHall/ActBtns/Img_sckk.png",
        "hall/Image/NewGoldHall/ActBtns/Img_sclb.png",
        "hall/Image/NewGoldHall/ActBtns/Img_wxjxlb.png",
        "hall/Image/NewGoldHall/ActBtns/Img_xyrw1.png",
        "hall/Image/NewGoldHall/ActBtns/bjmrt_jnrk_tit.png",
        "hall/Image/NewGoldHall/ActBtns/bjmrt_rk_jt02.png",
        "hall/Image/NewGoldHall/ActBtns/bjmrt_rk_tit_01jdt.png",
        "hall/Image/NewGoldHall/ActBtns/bjmrt_rk_tit_02jdt.png",
        "hall/Image/NewGoldHall/ActBtns/bjmrt_rk_tit_02jdt2.png",
        "hall/Image/NewGoldHall/ActBtns/bjmrt_rk_tit_wq.png",
    };

    /** {atlasX, atlasY, width, height, rotated, offsetX, offsetY,
     * sourceWidth, sourceHeight} for gold_hall_act_buttons. */
    public static final int[][] ACT_BUTTON_FRAMES = {
        {151, 498, 157, 152, 1, 0, -4, 157, 159},
        {155, 657, 148, 151, 0, 1, -11, 180, 180},
        {1, 498, 164, 148, 1, 0, 0, 164, 148},
        {303, 337, 150, 146, 1, 1, -7, 157, 159},
        {1, 178, 157, 159, 0, 0, 0, 157, 159},
        {154, 823, 157, 149, 1, 0, -5, 157, 159},
        {304, 160, 139, 134, 1, 4, -13, 157, 159},
        {1, 1, 164, 175, 0, 8, 2, 180, 180},
        {1, 664, 157, 152, 1, 0, -4, 157, 159},
        {160, 178, 157, 142, 1, 0, -9, 157, 159},
        {1, 823, 157, 151, 1, 0, -4, 157, 159},
        {1, 339, 157, 157, 0, 0, -1, 157, 159},
        {167, 1, 157, 136, 1, 0, -12, 157, 159},
        {160, 337, 157, 141, 1, 0, -9, 157, 159},
        {172, 982, 99, 35, 0, 0, 0, 99, 35},
        {440, 75, 119, 124, 0, 0, 0, 119, 124},
        {273, 982, 110, 13, 0, 0, 0, 110, 13},
        {1, 982, 169, 33, 0, 0, 0, 169, 33},
        {305, 1, 254, 72, 0, 0, 0, 254, 72},
        {273, 997, 23, 10, 1, -1, 0, 24, 10},
    };

    /** Android resource name of the gold_hall_pop atlas bitmap. */
    public static final String POP_RESOURCE = "gold_hall_pop";

    /** gold_hall_pop atlas bitmap size. */
    public static final int POP_WIDTH = 2046;

    public static final int POP_HEIGHT = 2042;

    /** Frame names of gold_hall_pop, aligned with POP_FRAMES. */
    public static final String[] POP_NAMES = {
        "hall/Image/NewGoldHall/Pop/Btn_an.png",
        "hall/Image/NewGoldHall/Pop/Btn_gm.png",
        "hall/Image/NewGoldHall/Pop/Btn_guanbi.png",
        "hall/Image/NewGoldHall/Pop/Btn_huang_1.png",
        "hall/Image/NewGoldHall/Pop/Btn_lan_1.png",
        "hall/Image/NewGoldHall/Pop/Btn_tc_sz1.png",
        "hall/Image/NewGoldHall/Pop/Btn_tc_sz2.png",
        "hall/Image/NewGoldHall/Pop/Btn_tc_sz3.png",
        "hall/Image/NewGoldHall/Pop/Btn_tc_xz_di1.png",
        "hall/Image/NewGoldHall/Pop/Btn_tc_xz_di2.png",
        "hall/Image/NewGoldHall/Pop/Btn_tc_xzdi1.png",
        "hall/Image/NewGoldHall/Pop/Btn_tc_xzdi2.png",
        "hall/Image/NewGoldHall/Pop/Img_cl.png",
        "hall/Image/NewGoldHall/Pop/Img_heng.png",
        "hall/Image/NewGoldHall/Pop/Img_res.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_add.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_dui.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_huang_big.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_huang_di1.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_huang_di2.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_huang_small.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_huang_zuo.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_suo.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_sz1.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_sz2.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_title1.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_title2.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_title3.png",
        "hall/Image/NewGoldHall/Pop/Img_tc_title4.png",
        "hall/Image/NewGoldHall/Pop/Img_tile.png",
        "hall/Image/NewGoldHall/Pop/Img_xz.png",
    };

    /** {atlasX, atlasY, width, height, rotated, offsetX, offsetY,
     * sourceWidth, sourceHeight} for gold_hall_pop. */
    public static final int[][] POP_FRAMES = {
        {1, 916, 342, 147, 0, 0, 0, 342, 147},
        {1933, 1981, 60, 80, 1, 0, 0, 60, 80},
        {197, 1175, 53, 54, 1, 0, 0, 53, 54},
        {1, 1065, 332, 108, 0, 0, 0, 332, 108},
        {345, 916, 332, 109, 1, 0, 0, 332, 109},
        {121, 1175, 73, 74, 1, 0, 0, 73, 74},
        {885, 940, 58, 59, 1, -2, -2, 62, 64},
        {1976, 1871, 62, 64, 1, 0, 0, 62, 64},
        {956, 1658, 322, 184, 1, 0, 0, 322, 184},
        {1976, 1308, 273, 46, 1, -1, -69, 322, 184},
        {485, 689, 398, 138, 0, 0, 0, 398, 138},
        {485, 829, 398, 138, 0, 0, 0, 398, 138},
        {1, 1658, 374, 953, 1, 0, 0, 375, 953},
        {1, 2034, 1168, 1, 0, 0, 0, 1168, 1},
        {1020, 1982, 33, 33, 0, 0, 0, 33, 33},
        {885, 816, 60, 62, 1, 0, 0, 60, 62},
        {885, 878, 60, 62, 1, 0, 0, 60, 62},
        {957, 1, 1655, 285, 1, 0, 0, 1655, 285},
        {1, 689, 482, 225, 0, 0, 0, 482, 225},
        {1, 1, 954, 566, 0, 0, 0, 954, 566},
        {1, 569, 944, 118, 0, 0, 0, 944, 118},
        {1171, 1658, 321, 803, 1, 0, 0, 321, 803},
        {956, 1982, 50, 62, 1, 0, 0, 60, 62},
        {1142, 1981, 789, 39, 0, 0, 0, 789, 39},
        {1976, 1, 789, 39, 1, 0, 0, 789, 39},
        {885, 689, 125, 64, 1, 0, 0, 125, 64},
        {1976, 792, 260, 69, 1, 0, 0, 260, 69},
        {1976, 1583, 151, 66, 1, 0, 0, 151, 66},
        {1976, 1736, 133, 67, 1, 0, 0, 133, 67},
        {1976, 1054, 252, 67, 1, 0, 0, 252, 67},
        {1, 1175, 118, 118, 0, 0, 0, 118, 118},
    };

}
